name: Staging Model Deployment for yape-mlstacks-2
'on':
  workflow_dispatch:
    inputs:
      modelUri:
        type: string
        description: URI of model to deploy, in the format models:/<model-name>/<version-id>
        required: true
env:
  DATABRICKS_HOST: https://adb-6832525285606128.8.azuredatabricks.net
  NODE_TYPE_ID: Standard_D3_v2
jobs:
  staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Generate AAD Token
      run: ./.github/workflows/scripts/generate-aad-token.sh ${{ secrets.stagingAzureSpTenantId
        }} ${{ secrets.stagingAzureSpApplicationId }} ${{ secrets.stagingAzureSpClientSecret
        }}
    - name: Deploy model
      env:
        MLFLOW_TRACKING_URI: databricks
      run: 'pip install mlflow

        python yape-mlstacks-2/deployment/model_deployment/deploy.py "${{ github.event.inputs.modelUri
        }}" "staging"

        '
